name: mobx_dart_angular
description: MobX Dart autorun directive for AngularDart.

# version: 0.0.1
# author: radzish <radzish@gmail.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  angular: ^6.0.0-alpha
  mobx: ^0.2.1+1
